version: 2
updates:
  - package-ecosystem: devcontainers
    directory: /
    schedule:
      interval: monthly
    groups:
      all:
        patterns: ["*"]

  - package-ecosystem: docker
    directory: /.devcontainer
    schedule:
      interval: monthly
    groups:
      all:
        patterns: ["*"]
